package algorithm.euler;

import algorithm.TestCase;

import java.io.IOException;
import java.text.ParseException;

public class Problem002 implements TestCase {

    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with and, the first terms will be:
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    @Override
    public void test() throws ParseException, IOException {
        int sum = 2;
        int a = 1, b = 2;
        
        while (b <= 4000000) {
            int next = a + b;
            if (next > 4000000) break;
            if (next % 2 == 0) {
                sum += next;
            }
            a = b;
            b = next;
        }
        
        System.out.println(sum);
    }
}
